using UnityEngine;

namespace Nesur.Core {
    public class Singleton<T> : MonoBehaviour where T : Component {
        private static T _instance;

        public static T Instance => _instance;

        public static T AutoGeneratedInstance {
            get {
                if (!_instance) {
                    CreateInstance();
                }

                return _instance;
            }
        }

        private static void CreateInstance() {
            var objectOfType = FindAnyObjectByType<T>();
            if (!objectOfType) {
                var newInstance = new GameObject($"{typeof(T).Name} Auto-Generated");
                _instance = newInstance.AddComponent<T>();
            }
            else {
                _instance = objectOfType;
            }
        }

        protected virtual void Awake() {
            if (transform.parent != null) {
                transform.SetParent(null);
            }

            if (_instance == null) {
                _instance = this as T;
                DontDestroyOnLoad(gameObject);
            }
            else {
                Destroy(gameObject);
            }
        }
    }
}